filter:
    excluded_paths: [app/config,app/config/*]

tools:
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_cpd:
        enabled: true
        excluded_dirs: [,app/config,app/config/*]
    php_pdepend:
        enabled: true
        excluded_dirs: [app/config,app/config/*]
